# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 01350412b72494d639ec2acf28d5c00fcf1f56d74453ec922593cdda9f011502c8641233e544de67f362312a269ebacd4a88f756b905f581e983b088989611d0

test:
  secret_key_base: a100c6fb0bc2ef85912397393f4aad9a32f52dba7a1d75540529426e09df25bcf5cb01e7f667d6e40413c4bcc2e52f627df4696d33dd71df333b3526bba47d73

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
